version: '3.8'
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "infnet-guia-website"
    stdin_open: true
    ports:
      - 3000:3000
  database:
    image: mysql:8.0
    container_name: "infnet-guia-website-database"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:       